export 'package:flutter/material.dart';
export 'package:xtramiler/screen/home.dart';
export 'package:xtramiler/screen/about_us.dart';
export 'package:xtramiler/screen/help.dart';
export 'package:xtramiler/screen/flash.dart';
export 'package:xtramiler/screen/index.dart';
export 'package:xtramiler/screen/login.dart';
export 'package:xtramiler/screen/register.dart';
export 'package:xtramiler/modules/inputbox.dart';
