export 'package:flutter/material.dart';
export 'package:xtramiler/screen/home.dart';
export 'package:xtramiler/screen/about_us.dart';
export 'package:xtramiler/screen/help.dart';
export 'package:xtramiler/screen/flash.dart';
export 'package:xtramiler/screen/signin.dart';
export 'package:xtramiler/screen/signup.dart';
export 'package:xtramiler/components/inputbox.dart';
export 'package:xtramiler/components/custombutton.dart';
